# Generated by Django 4.2.5 on 2023-10-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_isdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
            ],
        ),
    ]
