# Generated by Django 4.2.5 on 2023-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeedback',
            name='rating',
            field=models.PositiveIntegerField(default=3, verbose_name='Rating'),
        ),
    ]
