# Generated by Django 4.2.5 on 2023-10-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeedback',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_feedbacks', to='blog.post'),
        ),
    ]
